const express = require("express");
const rout = express.Router();
const user = require("../controller/userContoller");
const product = require('../controller/productController');
const coupon = require("../controller/couponController");
const order = require("../controller/orderController");
const address = require("../controller/addressController");
const auth = require('../middleware/auth');

rout.get("/", user.loadHome);
rout.get("/home", user.loadHome);
rout.get("/signin", auth.isNOtLogged, user.loadSignin);
rout.get("/signup", auth.isNOtLogged, user.loadSignup);
rout.get("/otp", auth.isNOtLogged, user.loadOtp);
rout.get("/sendotp", auth.isNOtLogged, user.sentOtp);
rout.get("/logout", auth.isLogged, user.loguot);
rout.get("/productDetails/:id", user.loadProductDetails);
rout.get('/cart',auth.isLogged, user.loadCart);
rout.get('/addtoCart', auth.isLogged, user.addToCart);
rout.get('/addtoCartProduct', auth.isLogged, user.addToCartProduct);
rout.get('/deleteCart', auth.isLogged, user.deleteCart);
rout.get("/verify", auth.isNOtLogged, user.loadOtp);
rout.get('/shop',user.loadShop);
rout.get("/forgotPassword", auth.isNOtLogged, user.forgotPassword);
rout.get("/wishlist", auth.isLogged, user.loadwislist);
rout.get("/addtoWishlist", auth.isLogged, user.addtoWishlist);
rout.get("/removeWishlist", auth.isLogged, user.removeWishlist);
rout.get("/checkout", auth.isLogged, order.loadCheckout);
rout.get("/order-success/:id", auth.isLogged, order.loadSucsses);
rout.get("/paypal-success/:orderId", auth.isLogged, order.paypal);
rout.get("/paypal-cancel/:orderId", auth.isLogged, order.cancel);
rout.get("/order", auth.isLogged, order.loadOrder);
rout.get("/invoice/:id", auth.isLogged, order.orderInvoice);
rout.get("/wallet", auth.isLogged, order.loadWallet);
rout.get("/blog", user.loadBlog);
rout.get("/profile", auth.isLogged, address.loadProfile);
rout.get("/deleteAddress/:id",address.deleteAddress)
rout.get("/cart/coupon", auth.isLogged, coupon.applyCoupon);
rout.get("/home/getProduct", auth.isLogged, user.getProducts);
rout.get("/getProduct", auth.isLogged, user.getProducts);
rout.get("/filter", user.filterProducts);
rout.get("/referral", user.loadReferral);
rout.get("/addMoney", order.addMoney);
rout.post("/razorpay-success", auth.isLogged, order.razorpaySuccess);
rout.post("/addReview", auth.isLogged, product.rating);
rout.post("/signup", auth.isNOtLogged, user.verifySignup);
rout.post("/signin", auth.isNOtLogged, user.verifySignin);
rout.post("/verify", auth.isNOtLogged, user.verifyotp);
rout.post("/changePassword", auth.isNOtLogged, user.changePassword);
rout.post("/addtoCart", auth.isLogged, user.addToCartProduct);
rout.post("/cancelOrder/:id", auth.isLogged, order.cancelOrder);
rout.post("/returnOrder/:id", auth.isLogged, order.returnOrder);
rout.post("/cart/placeOrder", auth.isLogged, order.placeOrder);
rout.post("/addAddress", auth.isLogged, address.addAddress);
rout.post("/editAddress/:id", auth.isLogged, address.editAddress);
module.exports = rout;